### ISSUE TITLE
Korektně reagovat na chyby z banky

### ISSUE THREAD

**Issue by Vitexus** [VitexSoftware/abraflexi-matcher#4]
```
01/12/2024 15:17:1 💀 ❲AbraFlexi StahniBanku⦒AbraFlexi\\Banka❳ Unparsed error: {\"winstrom\":{\"@version\":\"1.0\",\"success\":\"false\",\"stats\":{\"created\":\"0\",\"updated\":\"0\",\"deleted\":\"0\",\"skipped\":\"0\",\"failed\":\"2\"},\"results\":[{\"code\":\"Výpis 0 pro účet 22222227/2010 -  Počet položek 0\",\"errors\":[{\"message\":\"Během stahování výpisu pro účet HLAVNI FIO (222222227/2010) došlo k chybě.\\nNedodržujete minimální interval 30 sekund mezi dotazy na daný token (bez ohledu na typ formátu).\"}]},{\"code\":\"Výpis 0 pro účet 20000007/2010 -  Počet položek 0\",\"errors\":[{\"message\":\"Během stahování výpisu pro účet EURO FIO (290000003/2010) došlo k chybě.\\nNedodržujete minimální interval 30 sekund mezi dotazy na daný token (bez ohledu na typ formátu).\"}]}]}}
01/12/2024 15:17:1 💀 ❲AbraFlexi StahniBanku⦒AbraFlexi\\RO::parseResponse:124❳ AbraFlexi\\Banka: Problem 
PHP Fatal error:  Uncaught AbraFlexi\\Exception: AbraFlexi\\Banka: Problem  in /usr/share/php/AbraFlexi/RO.php:1234
Stack trace:
#0 /usr/share/php/AbraFlexi/RW.php(124): AbraFlexi\\RO->parseResponse()
#1 /usr/share/php/AbraFlexi/RO.php(1001): AbraFlexi\\RW->parseResponse()
#2 /usr/share/php/AbraFlexi/Banka.php(55): AbraFlexi\\RO->performRequest()
#3 /usr/lib/abraflexi-matcher/StahniBanku.php(22): AbraFlexi\\Banka->stahnoutVypisyOnline()
#4 {main}
  thrown in /usr/share/php/AbraFlexi/RO.php on line 1234
```

**Comment by Vitexus** [comment]
Vyřešeno
